# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Djavax.net.ssl.trustStoreType=Windows-ROOT
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15.5
# Mod Properties
mod_version=1.4
maven_group=app.qwertz
archives_base_name=ModernConfig
# Dependencies
# check this on https://fabricmc.net/develop
fabric_version=0.156.0+26.2
