# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Djavax.net.ssl.trustStoreType=Windows-ROOT
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.16.3
# Mod Properties
mod_version=1.5
maven_group=app.qwertz
archives_base_name=ModernConfig
# Dependencies
# check this on https://fabricmc.net/develop
fabric_version=0.161.0+26.3
